name: schedule_app
version: 1.0.0+2
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  liquid_glass_renderer: 0.2.0-dev.4

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
